### ISSUE TITLE
Links of the Content Guidelines Overview are broken

### ISSUE THREAD

**Issue by paulehoffman** [ietf/authors.ietf.org#78]
The links on https://github.com/ietf/authors.ietf.org/blob/main/content-guidelines-overview.md are broken. I wanted to edit the "Required Content" page, but I get a 404 from that URL.

**Comment by rjsparks** [comment]
I don't think the github view of the pages is intended to be navigable that way. @NGPixel could say more. But what you can do is go to the markdown document for that page in the repo. (add .md to the link).

**Comment by JayDaley** [comment]
These links are not meant to work from the repo.  This repo contains the code for the wiki, it is not intended to be a working set of wiki pages itself.  There are multiple reasons for this, including:
1. Internal links (like these) don't work because the page naming is different.  In wiki.js pages are referenced by slug but in GitHub they are referenced by filename and so these links are missing a `.md` on the end for GH but that would break them for wiki.js
2. The markdown syntax on the two sites is quite different.  For example, Wiki.js uses markdown attributes for blockquote styling, which are expressed in curly braces **after** the bq, such as `{.is-info}`, where are GH uses [completely unique markup](https://github.com/orgs/community/discussions/16925) **before** the code such as `[!NOTE]`.
